# Generated by Django 5.1.1 on 2024-09-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
